export const SET_ALL_POSTS = "SET_ALL_POSTS";
export const SET_ALL_POSTS_SUCCESS = "SET_ALL_POSTS_SUCCESS";
export const SET_ALL_POSTS_ERROR = "SET_ALL_POSTS_ERROR";

export const SET_ALL_USERS = "SET_ALL_USERS";
export const SET_ALL_USERS_SUCCESS = "SET_ALL_USERS_SUCCESS";
export const SET_ALL_USERS_ERROR = "SET_ALL_USERS_ERROR";

export const GET_COMMENTS_POST = "GET_COMMENTS_POST";
export const GET_COMMENTS_POST_SUCCESS = "GET_COMMENTS_POST_SUCCESS";
export const GET_COMMENTS_POST_ERROR = "GET_COMMENTS_POST_ERROR";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_USER_POSTS = "GET_USER_POSTS";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_ERROR = "GET_USER_POSTS_ERROR";

